# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Korge Game Engine
email: soywiz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Modern Kotlin Game Engine for Desktop, Web and Mobile.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://docs.korge.soywiz.com" # the base hostname & protocol for your site
doc_base_url: https://github.com/soywiz/docs.korge.soywiz.com
blog_url: ""
project_url: https://github.com/soywiz/korge
google_search_id: 001447907640164080602:ej0h0w0ufr0
twitter_username: korge
github_username:  soywiz
disqus_id: ""

# Build settings
markdown: kramdown
