title: Korlibs
email: soywiz@gmail.com
description: Modern Kotlin Common Libraries for Full Stack development
baseurl: ""
url: "https://korlibs.soywiz.com"
doc_base_url: https://github.com/korlibs/korlibs.github.io
blog_url: ""
project_url: https://github.com/korlibs
google_search_id: 001447907640164080602:ej0h0w0ufr0
github_username:  korlibs
disqus_id: ""
markdown: kramdown
